from __future__ import annotations

import logging
import os
from typing import Any, Dict, List

from app.self_heal.scaffold_engine import scaffold_engine

logger = logging.getLogger(__name__)


class CodeEmitterEngine:
    """
    Level 2:
    - reads generated blueprints from ScaffoldEngine
    - builds concrete backend/frontend file artifacts in memory
    - prepares PR payload structures for downstream GitHub bridge integration
    - never raises to caller
    """

    def __init__(self) -> None:
        self.generated_artifacts: Dict[str, Dict[str, Any]] = {}
        self.auto_emit_enabled = os.getenv("AUTO_CODE_EMISSION_ENABLED", "false").strip().lower() in (
            "1",
            "true",
            "yes",
            "on",
        )
        self.auto_pr_backend_enabled = os.getenv("AUTO_PR_BACKEND_ENABLED", "false").strip().lower() in (
            "1",
            "true",
            "yes",
            "on",
        )
        self.auto_pr_frontend_enabled = os.getenv("AUTO_PR_FRONTEND_ENABLED", "false").strip().lower() in (
            "1",
            "true",
            "yes",
            "on",
        )

    def emit_code_plan(self, capability_name: str) -> Dict[str, Any]:
        blueprint = scaffold_engine.generated_blueprints.get(capability_name)

        if not blueprint:
            logger.warning("CODE_EMITTER_BLUEPRINT_NOT_FOUND %s", capability_name)
            return {}

        code_plan = {
            "models_file": f"{capability_name}_models.py",
            "routes_file": f"{capability_name}_routes.py",
            "agents_file": f"{capability_name}_agents.py",
            "views_path": f"{capability_name}_views/",
            "models": blueprint.get("models", []),
            "routes": blueprint.get("routes", []),
            "agents": blueprint.get("agents", []),
            "views": blueprint.get("views", []),
        }

        self.generated_artifacts[capability_name] = code_plan
        logger.warning("CODE_EMITTER_PLAN_READY %s", capability_name)

        if self.auto_emit_enabled:
            artifacts = self._build_artifacts(capability_name, code_plan)
            self.generated_artifacts[capability_name]["artifacts"] = artifacts
            logger.warning("CODE_EMITTER_ARTIFACTS_READY %s", capability_name)

            pr_payload = self._build_pr_payload(capability_name, artifacts)
            self.generated_artifacts[capability_name]["pr_payload"] = pr_payload
            logger.warning("CODE_EMITTER_PR_PAYLOAD_READY %s", capability_name)

        return self.generated_artifacts[capability_name]

    def _build_artifacts(self, capability_name: str, code_plan: Dict[str, Any]) -> Dict[str, str]:
        models = list(code_plan.get("models", []))
        routes = list(code_plan.get("routes", []))
        agents = list(code_plan.get("agents", []))
        views = list(code_plan.get("views", []))

        artifacts: Dict[str, str] = {}

        artifacts[f"app/generated/{code_plan['models_file']}"] = self._render_models_file(
            capability_name=capability_name,
            models=models,
        )
        artifacts[f"app/generated/{code_plan['routes_file']}"] = self._render_routes_file(
            capability_name=capability_name,
            routes=routes,
        )
        artifacts[f"app/generated/{code_plan['agents_file']}"] = self._render_agents_file(
            capability_name=capability_name,
            agents=agents,
        )

        for view_name in views:
            artifacts[f"frontend/generated/{code_plan['views_path']}{view_name}.tsx"] = self._render_view_file(
                capability_name=capability_name,
                view_name=view_name,
            )

        return artifacts

    def _build_pr_payload(self, capability_name: str, artifacts: Dict[str, str]) -> Dict[str, Any]:
        backend_files = []
        frontend_files = []

        for path, content in artifacts.items():
            item = {"path": path, "content": content}
            if path.startswith("frontend/"):
                frontend_files.append(item)
            else:
                backend_files.append(item)

        payload: Dict[str, Any] = {
            "capability_name": capability_name,
            "title": f"feat: emit runtime artifacts for {capability_name}",
            "backend_enabled": self.auto_pr_backend_enabled,
            "frontend_enabled": self.auto_pr_frontend_enabled,
            "backend_files": backend_files,
            "frontend_files": frontend_files,
        }
        return payload

    def _render_models_file(self, capability_name: str, models: List[str]) -> str:
        blocks: List[str] = [
            "from __future__ import annotations",
            "",
            '"""Auto-generated by Orkio CodeEmitterEngine."""',
            "",
        ]

        for model_name in models:
            fields_block = [
                f"class {model_name}:",
                '    """Generated placeholder model scaffold."""',
                "    def __init__(self, **kwargs):",
                "        for key, value in kwargs.items():",
                "            setattr(self, key, value)",
                "",
            ]
            blocks.extend(fields_block)

        if len(models) == 0:
            blocks.extend(
                [
                    "# No models requested for this capability.",
                    "",
                ]
            )

        return "\n".join(blocks).rstrip() + "\n"

    def _render_routes_file(self, capability_name: str, routes: List[str]) -> str:
        safe_tag = capability_name.replace("-", "_")
        lines: List[str] = [
            "from __future__ import annotations",
            "",
            "from fastapi import APIRouter",
            "",
            f'router = APIRouter(prefix="/generated/{safe_tag}", tags=["generated:{safe_tag}"])',
            "",
        ]

        if not routes:
            lines.extend(
                [
                    '@router.get("/health")',
                    "def generated_health():",
                    f'    return {{"status": "ok", "capability": "{capability_name}"}}',
                    "",
                ]
            )
            return "\n".join(lines).rstrip() + "\n"

        for route in routes:
            suffix = route.strip("/").replace("/", "_").replace("-", "_") or "root"
            lines.extend(
                [
                    f'@router.get("/{suffix}")',
                    f"def {suffix}_handler():",
                    f'    return {{"capability": "{capability_name}", "route": "{route}", "status": "generated"}}',
                    "",
                ]
            )

        return "\n".join(lines).rstrip() + "\n"

    def _render_agents_file(self, capability_name: str, agents: List[str]) -> str:
        lines: List[str] = [
            "from __future__ import annotations",
            "",
            '"""Auto-generated agent registry scaffold."""',
            "",
            "GENERATED_AGENTS = [",
        ]

        for agent in agents:
            lines.append(f'    "{agent}",')

        lines.extend(
            [
                "]",
                "",
                "def list_generated_agents():",
                "    return GENERATED_AGENTS",
                "",
            ]
        )

        return "\n".join(lines).rstrip() + "\n"

    def _render_view_file(self, capability_name: str, view_name: str) -> str:
        return f"""export default function {view_name}() {{
  return (
    <div style={{ padding: 24 }}>
      <h1>{view_name}</h1>
      <p>Generated by Orkio for capability: {capability_name}</p>
    </div>
  );
}}
"""

code_emitter = CodeEmitterEngine()
